from __future__ import annotations

from copy import deepcopy
from typing import Any

DEFAULT_MOTION_PROFILE: dict[str, Any] = {
    "translation": {
        "startSpeed": 100,
        "maxSpeed": 1000,
        "accTimeSec": 0.05,
        "decTimeSec": 0.05,
    },
    "rotation": {
        "startSpeed": 0.3,
        "maxSpeed": 3,
        "accTimeSec": 0.02,
        "decTimeSec": 0.02,
    },
}

DEFAULT_SOFT_LIMITS: dict[str, Any] = {
    "x": {"min": -25000, "max": 25000},
    "y": {"min": -37500, "max": 37500},
    "z": {"min": -37500, "max": 37500},
    "roll": {"min": -180, "max": 180},
    "pitch": {"min": -70, "max": 70},
    "yaw": {"min": -7.5, "max": 7.5},
}

DEFAULT_CONFIG: dict[str, Any] = {
    "hal": {
        "baseUrl": "http://localhost:8091",
        "wsUrl": "ws://localhost:8091/ws/telemetry",
        "axisCount": 12,
        "apiConfirmed": False,
        "mode": "real",
        "timeoutMs": 5000,
        "ltdmcDllPath": "F:/E2EAPP_MicroMani/hal/vendor/leishine/bin/LTDMC.dll",
        "ltdmcLibPath": "F:/E2EAPP_MicroMani/hal/vendor/leishine/lib/x64/LTDMC.lib",
        "dhdDllPath": "F:/E2EAPP_MicroMani/hal/vendor/force_dimension/bin/dhd64.dll",
    },
    "cameras": {
        "global": "AR0234 / index 2",
        "globalIdentity": "USB\\VID_1D6B&PID_0102&MI_00\\7&235CBC02&0&0000",
        "wristLeft": "IMX258 / index 1",
        "wristLeftIdentity": "USB\\VID_0EDC&PID_3080&MI_00\\7&38B4EA25&0&0000",
        "wristRight": "IMX258 / index 0",
        "wristRightIdentity": "USB\\VID_0EDC&PID_3080&MI_00\\6&1BBFDB86&0&0000",
        "previewResolution": "640x480",
        "globalResolution": "640x480",
        "wristLeftResolution": "640x480",
        "wristRightResolution": "640x480",
        "fps": 30,
    },
    "force": {
        "leftIp": "Dev5/ai0:5",
        "rightIp": "Dev3/ai0:5",
        "port": 49152,
        "sampleHz": 200,
        "recordWindowSamples": 0,
        "tareSamples": 0,
        "certificateConfirmed": False,
        "calibrationEnabled": True,
        "leftCalibrationPath": "C:/Program Files (x86)/ATI Industrial Automation/ATIDAQFT.NET/FT32918.cal",
        "rightCalibrationPath": "C:/Program Files (x86)/ATI Industrial Automation/ATIDAQFT.NET/FT38799.cal",
        "inputMode": "DIFF",
        "voltageMin": -10,
        "voltageMax": 10,
        "lowpassEnabled": True,
        "lowpassCutoffHz": 10,
        "swapHands": False,
    },
    "motion": {
        "leftCardNo": 1,
        "rightCardNo": 0,
        "motionThreadHz": 1000,
        "jogStepUm": 50,
        "jogStepDeg": 0.05,
        "yawSoftLimitDeg": 7.5,
        "positionSource": "dmc_get_position",
        "origin": {
            "valid": False,
            "leftValid": False,
            "rightValid": False,
            "leftPulse": [0.0] * 6,
            "rightPulse": [0.0] * 6,
            "updatedAt": 0,
        },
        "homeOnStartup": {
            "enabled": False,
            "mode": "work_origin",
        },
        "leftProfile": deepcopy(DEFAULT_MOTION_PROFILE),
        "rightProfile": deepcopy(DEFAULT_MOTION_PROFILE),
        "leftSoftLimits": deepcopy(DEFAULT_SOFT_LIMITS),
        "rightSoftLimits": deepcopy(DEFAULT_SOFT_LIMITS),
    },
    "gripper": {
        "leftPort": "COM8",
        "rightPort": "COM9",
        "baudrate": 115200,
        "leftSlaveId": 10,
        "rightSlaveId": 9,
        "strokeMm": 26,
        "targetLeftMm": 13,
        "targetRightMm": 13,
        "leftEnabled": False,
        "rightEnabled": False,
        "commandForceLimitN": 8,
        "commandSpeed": 10,
        "commandTorque": 1,
        "sampleMode": "dual_worker",
        "sampleHz": 30,
        "sampleStaleMs": 500,
        "sampleEnableOnNegative": True,
        "workerCommandTimeoutSec": 2.0,
        "forceFeedbackAvailable": False,
        "jodellDllPath": (
            "F:/E2EAPP_MicroMani/backend/vendor/jodell/jodellTool.dll"
        ),
    },
    "safety": {
        "fxyWarnN": 2,
        "fxyStopN": 4,
        "fzWarnN": 3,
        "fzStopN": 5,
        "momentWarnNm": 0.02,
        "momentStopNm": 0.04,
        "yawSoftLimitDeg": 7.5,
        "watchdogMs": 50,
    },
    "zmq": {
        "observationPush": "tcp://127.0.0.1:8082",
        "actionPull": "tcp://127.0.0.1:8083",
        "timeoutMs": 50,
    },
    "storage": {
        "datasetRoot": "~/.appstation/datasets",
        "recordFps": 30,
        "videoCrf": 23,
        "pushToHub": False,
    },
    "auto": {
        "allowHardwareDispatch": False,
        "translationStepUm": 200,
        "rotationStepDeg": 0.2,
        "translationVelocityUmS": 1000,
        "rotationVelocityDegS": 0.5,
    },
    "picoVision": {
        "ip": "10.90.132.174",
        "adbPort": 5555,
        "videoPort": 12345,
        "commandPort": 13579,
        "gateway": "10.90.0.1",
        "ifIndex": 13,
        "rotation": "ccw90",
        "cameraSource": "global",
        "scriptsDir": "F:/ICFNewProject/PicoWirelessTools",
        "senderBuildDir": "F:/ICFNewProject/QSerialTest3.0/QSerialTest/QSerialTest/tools/pico_mono_sender/build",
    },
    "teleop": {
        "coarse": 1,
        "medium": 0.35,
        "fine": 0.08,
        "inputIntervalMs": 10,
        "commandIntervalMs": 10,
        "leftOpenId": 0,
        "rightOpenId": 1,
        "leftConnected": False,
        "rightConnected": False,
        "leftGravityCompensation": True,
        "rightGravityCompensation": True,
        "leftForceFeedback": False,
        "rightForceFeedback": False,
        "leftTranslationScale": 0.24,
        "rightTranslationScale": 0.3,
        "leftRotationScale": 0.18,
        "rightRotationScale": 0.18,
        "translationDeadzone": 0.00002,
        "rotationDeadzone": 0.08,
        "requireClutch": False,
        "stabilityMode": "track",
        "tcpFallbackPort": 12345,
        "gripperTeleop": {
            "enabled": False,
            "loopHz": 100,
            "leftGapMinMm": 0.0,
            "leftGapMaxMm": 25.0,
            "rightGapMinMm": 0.0,
            "rightGapMaxMm": 25.0,
            "openThreshold": 0.30,
            "closeThreshold": 0.70,
            "gripSpeed": 128,
            "gripTorque": 192,
            "releaseSpeed": 255,
            "releaseTorque": 64,
            "objectDetectMargin": 10,
            "buttonFallback": True,
            "diagLog": False,
        },
    },
    "wsl": {
        "distro": "Ubuntu-22.04",
        "condaEnv": "lerobot",
        "pythonPath": "/home/user/miniconda3/envs/lerobot/bin/python",
        "pendingWindowsValidation": True,
    },
}


def default_config() -> dict[str, Any]:
    return deepcopy(DEFAULT_CONFIG)
