import type { AppConfig, DiagnosticItem, LogChannel } from './types'

export const axisNames = [
  'L-X',
  'L-Y',
  'L-Z',
  'L-RX',
  'L-RY',
  'L-RZ',
  'R-X',
  'R-Y',
  'R-Z',
  'R-RX',
  'R-RY',
  'R-RZ',
]

export const forceChannels = ['Fx', 'Fy', 'Fz', 'Mx', 'My', 'Mz']

export const semanticAxes = ['X', 'Y', 'Z', 'Roll', 'Pitch', 'Yaw'] as const

export type RobotSide = 'left' | 'right'

export const armHardwareSpecs = {
  left: {
    label: '左机械臂',
    shortLabel: '左臂',
    cardNo: 1,
    configKey: 'Motion/LeftStageCardNo',
    axisOrder: [0, 1, 3, 5, 4, 2],
    stateOffset: 0,
    gripperPort: 'COM8',
    gripperSlaveId: 10,
    omegaDeviceId: 0,
    forceIpKey: 'leftIp',
  },
  right: {
    label: '右机械臂',
    shortLabel: '右臂',
    cardNo: 0,
    configKey: 'Motion/RightStageCardNo',
    axisOrder: [2, 0, 5, 8, 1, 7],
    stateOffset: 6,
    gripperPort: 'COM9',
    gripperSlaveId: 9,
    omegaDeviceId: 1,
    forceIpKey: 'rightIp',
  },
} as const

export const axisHardwareSpecs = [
  {
    axis: 'X',
    unit: 'µm',
    travel: '50 mm',
    model: 'KXL0605-C1-C',
    leftPulsePerUnit: 5000,
    rightPulsePerUnit: 5000,
    softLimit: '按标定工作原点配置',
    warning: false,
  },
  {
    axis: 'Y',
    unit: 'µm',
    travel: '75 mm',
    model: 'KXL06075-C1-G4',
    leftPulsePerUnit: 10000,
    rightPulsePerUnit: 10000,
    softLimit: '按标定工作原点配置',
    warning: false,
  },
  {
    axis: 'Z',
    unit: 'µm',
    travel: '75 mm',
    model: 'KXL06075-C1-G4',
    leftPulsePerUnit: 10000,
    rightPulsePerUnit: 10000,
    softLimit: '按标定工作原点配置',
    warning: false,
  },
  {
    axis: 'Roll',
    unit: '°',
    travel: '360°',
    model: 'KRW04360M-LC',
    leftPulsePerUnit: 1666.6667,
    rightPulsePerUnit: 1666.6667,
    softLimit: '按标定工作原点配置',
    warning: false,
  },
  {
    axis: 'Pitch',
    unit: '°',
    travel: '360°',
    model: 'KRW06360M-LC',
    leftPulsePerUnit: 2500,
    rightPulsePerUnit: 2500,
    softLimit: '建议 ±70° 起步验证',
    warning: false,
  },
  {
    axis: 'Yaw',
    unit: '°',
    travel: '±8°',
    model: 'KGW04040M-LC',
    leftPulsePerUnit: 3333.3333,
    rightPulsePerUnit: 3333.3333,
    softLimit: '必须 ≤ ±7.5°',
    warning: true,
  },
] as const

export const cameraHardwareSpecs = {
  global: {
    label: '全局相机',
    model: 'AR0234',
    device: 'AR0234 / index 1',
    rawResolution: '1920x1080',
    previewResolution: '640x480',
    fps: 30,
    lerobotKey: 'observation.images.global',
  },
  wrist_left: {
    label: '左腕相机',
    model: 'IMX258',
    device: 'IMX258 / index 2',
    rawResolution: '1920x1080',
    previewResolution: '640x480',
    fps: 30,
    lerobotKey: 'observation.images.wrist_left',
  },
  wrist_right: {
    label: '右腕相机',
    model: 'IMX258',
    device: 'IMX258 / index 0',
    rawResolution: '1920x1080',
    previewResolution: '640x480',
    fps: 30,
    lerobotKey: 'observation.images.wrist_right',
  },
} as const

export const nano17Spec = {
  model: 'ATI Nano-17 SI-12-0.12',
  range: {
    fxy: '±12 N',
    fz: '±17 N',
    moment: '±120 mN·m',
  },
  channels: 'Fx, Fy, Fz, Mx, My, Mz',
  port: 49152,
  rdtHz: 7000,
  fastDaqHz: 200,
} as const

export const omega7Spec = {
  translationWorkspace: 'Ø160 mm × 110 mm',
  rotationWorkspace: 'Roll 240° / Pitch 140° / Yaw 180°',
  gripperDistance: '25 mm',
  maxForceN: 12,
  maxGripperForceN: 8,
  sdkMaxHz: 4000,
  mapping: {
    x: 0.469,
    y: 0.455,
    z: 0.469,
    roll: 0.75,
    pitch: 1,
    yaw: 0.089,
  },
} as const

export const defaultMotionProfile = {
  translation: {
    startSpeed: 100,
    maxSpeed: 1000,
    accTimeSec: 0.05,
    decTimeSec: 0.05,
  },
  rotation: {
    startSpeed: 0.3,
    maxSpeed: 3,
    accTimeSec: 0.02,
    decTimeSec: 0.02,
  },
}

export const defaultSoftLimits = {
  x: { min: -40000000, max: 40000000 },
  y: { min: -20000000, max: 20000000 },
  z: { min: -20000000, max: 20000000 },
  roll: { min: -120000, max: 120000 },
  pitch: { min: -80000, max: 80000 },
  yaw: { min: -60000, max: 60000 },
}

export const logChannels: LogChannel[] = [
  '[HAL]',
  '[BACKEND]',
  '[CAMERA]',
  '[FORCE]',
  '[SAFETY]',
  '[ZMQ]',
  '[POLICY]',
  '[LEROBOT]',
  '[GRIPPER]',
]

export const channelColor: Record<LogChannel, string> = {
  '[HAL]': '#0d7c8a',
  '[BACKEND]': '#4b5563',
  '[CAMERA]': '#168a4a',
  '[FORCE]': '#b77900',
  '[SAFETY]': '#d83a52',
  '[ZMQ]': '#7353ba',
  '[POLICY]': '#2f6fed',
  '[LEROBOT]': '#c86a12',
  '[GRIPPER]': '#667085',
}

export const defaultDiagnostics: DiagnosticItem[] = [
  {
    key: 'hal-health',
    label: 'C++ HAL 连接',
    method: 'GET /health',
    metric: '<10ms',
    status: 'ok',
    remediation: '显示重连按钮，提示启动 HalServer.exe',
  },
  {
    key: 'ltdmc',
    label: 'LTDMC DLL 加载',
    method: 'HAL /health.ltdmc_ok',
    metric: 'true',
    status: 'pending',
    remediation: '检查 LTDMC.dll 路径、驱动和 Windows 控制卡',
    suspect: true,
  },
  {
    key: 'omega7',
    label: 'Omega.7 主手',
    method: 'HAL /health.omega7_ok',
    metric: '两台均 true',
    status: 'pending',
    remediation: '检查 USB、SDK 和两台主手枚举结果',
    suspect: true,
  },
  {
    key: 'ati-left',
    label: 'ATI Nano-17 左',
    method: 'NI-DAQmx Dev5/ai0:5',
    metric: '200 Hz',
    status: 'warn',
    remediation: '确认 NI-DAQmx、Dev5/ai0:5、DIFF 接线和 FT32918.cal',
    suspect: true,
  },
  {
    key: 'ati-right',
    label: 'ATI Nano-17 右',
    method: 'NI-DAQmx Dev3/ai0:5',
    metric: '200 Hz',
    status: 'warn',
    remediation: '确认 NI-DAQmx、Dev3/ai0:5、DIFF 接线和 FT38799.cal',
    suspect: true,
  },
  {
    key: 'cam-global',
    label: '相机 全局',
    method: '最近帧时间戳年龄',
    metric: '<100ms',
    status: 'ok',
    remediation: '重新枚举设备或降低分辨率',
  },
  {
    key: 'gripper',
    label: 'RS485 夹爪',
    method: 'pyserial 握手',
    metric: '两路 OK',
    status: 'pending',
    remediation: '确认 COM 端口、波特率和线序',
    suspect: true,
  },
  {
    key: 'wsl-policy',
    label: 'WSL2 PolicyServer',
    method: 'ZMQ PING/PONG',
    metric: '<50ms',
    status: 'pending',
    remediation: '检查 wsl --status、conda 环境和端口映射',
    suspect: true,
  },
]

export const defaultConfig: AppConfig = {
  hal: {
    baseUrl: 'http://localhost:8091',
    wsUrl: 'ws://localhost:8091/ws/telemetry',
    axisCount: 12,
    apiConfirmed: false,
  },
  cameras: {
    global: 'AR0234 / index 1',
    globalIdentity: 'USB\\VID_1D6B&PID_0102&MI_00\\6&1E9A8698&0&0000',
    wristLeft: 'IMX258 / index 2',
    wristLeftIdentity: 'USB\\VID_0EDC&PID_3080&MI_00\\7&38B4EA25&0&0000',
    wristRight: 'IMX258 / index 0',
    wristRightIdentity: 'USB\\VID_0EDC&PID_3080&MI_00\\6&1BBFDB86&0&0000',
    previewResolution: '640x480',
    globalResolution: '640x480',
    wristLeftResolution: '640x480',
    wristRightResolution: '640x480',
    fps: 30,
    tuning: {
      global: {
        autoExposure: false,
        exposure: -5.5,
        gain: 0,
        autoWhiteBalance: false,
      },
      wrist_left: {
        autoExposure: false,
        exposure: -6,
        gain: 0,
        autoWhiteBalance: false,
      },
      wrist_right: {
        autoExposure: false,
        exposure: -6,
        gain: 0,
        autoWhiteBalance: false,
      },
    },
  },
  force: {
    leftIp: 'Dev5/ai0:5',
    rightIp: 'Dev3/ai0:5',
    port: 49152,
    sampleHz: 200,
    recordWindowSamples: 0,
    tareSamples: 0,
    certificateConfirmed: false,
    calibrationEnabled: true,
    leftCalibrationPath: 'C:/Program Files (x86)/ATI Industrial Automation/ATIDAQFT.NET/FT32918.cal',
    rightCalibrationPath: 'C:/Program Files (x86)/ATI Industrial Automation/ATIDAQFT.NET/FT38799.cal',
    inputMode: 'DIFF',
    voltageMin: -10,
    voltageMax: 10,
    lowpassEnabled: true,
    lowpassCutoffHz: 10,
    swapHands: false,
  },
  motion: {
    leftCardNo: 1,
    rightCardNo: 0,
    motionThreadHz: 1000,
    jogStepUm: 50,
    jogStepDeg: 0.05,
    yawSoftLimitDeg: 60000,
    positionSource: 'dmc_get_position',
    workOriginStrategyVersion: 'icf_work_origin_20260513',
    origin: {
      valid: true,
      leftValid: true,
      rightValid: true,
      leftPulse: [100000, 0, -35179, 64833, 64839, -2947],
      rightPulse: [-233, -19221, 593101, 4427, -81110, -180],
      updatedAt: 1778586070000,
    },
    homeOnStartup: {
      enabled: false,
      mode: 'work_origin',
    },
    leftProfile: structuredClone(defaultMotionProfile),
    rightProfile: structuredClone(defaultMotionProfile),
    leftSoftLimits: structuredClone(defaultSoftLimits),
    rightSoftLimits: structuredClone(defaultSoftLimits),
  },
  gripper: {
    leftPort: 'COM8',
    rightPort: 'COM9',
    baudrate: 115200,
    leftSlaveId: 10,
    rightSlaveId: 9,
    strokeMm: 26,
    targetLeftMm: 13,
    targetRightMm: 13,
    leftEnabled: false,
    rightEnabled: false,
    commandForceLimitN: 8,
    commandSpeed: 10,
    commandTorque: 1,
    sampleMode: 'dual_worker',
    sampleHz: 30,
    sampleStaleMs: 500,
    sampleEnableOnNegative: true,
    workerCommandTimeoutSec: 2,
    forceFeedbackAvailable: false,
  },
  safety: {
    fxyWarnN: 2,
    fxyStopN: 4,
    fzWarnN: 3,
    fzStopN: 5,
    momentWarnNm: 0.02,
    momentStopNm: 0.04,
    yawSoftLimitDeg: 60000,
    watchdogMs: 50,
  },
  zmq: {
    observationPush: 'tcp://127.0.0.1:8082',
    actionPull: 'tcp://127.0.0.1:8083',
    timeoutMs: 50,
  },
  storage: {
    datasetRoot: '~/.appstation/datasets',
    recordFps: 30,
    videoCrf: 23,
    pushToHub: false,
  },
  auto: {
    allowHardwareDispatch: false,
    translationStepUm: 200,
    rotationStepDeg: 0.2,
    translationVelocityUmS: 1000,
    rotationVelocityDegS: 0.5,
  },
  picoVision: {
    ip: '10.90.132.174',
    adbPort: 5555,
    videoPort: 12345,
    commandPort: 13579,
    gateway: '10.90.0.1',
    ifIndex: 13,
    rotation: 'ccw90',
    cameraSource: 'global',
  },
  teleop: {
    coarse: 1,
    medium: 0.35,
    fine: 0.08,
    inputIntervalMs: 10,
    commandIntervalMs: 10,
    leftOpenId: 0,
    rightOpenId: 1,
    leftConnected: false,
    rightConnected: false,
    leftGravityCompensation: true,
    rightGravityCompensation: true,
    leftForceFeedback: false,
    rightForceFeedback: false,
    strategyVersion: 'icf_omega7_qserialtest_limits_20260513',
    swapHands: true,
    leftTranslationScale: 0.3,
    rightTranslationScale: 0.3,
    leftRotationScale: 0.1,
    rightRotationScale: 0.05,
    leftAxisOutputScale: [0.2, 0.2, 1, 1, 0.5, 0.1],
    rightAxisOutputScale: [0.2, 0.2, 1, 1, 0.5, 0.1],
    translationStepUm: 5000,
    rotationStepDeg: 0.2,
    translationStepLimitPulse: 4000,
    rotationStepLimitPulse: 1250,
    translationDeadzone: 0.00002,
    rotationDeadzone: 0.05,
    incrementalTranslationMinEffectiveDelta: 0.00005,
    incrementalTranslationReverseDeadzone: 0.0001,
    translationStartVelocityUmS: 300,
    translationMaxVelocityUmS: 4000,
    rotationStartVelocityDegS: 0.25,
    rotationMaxVelocityDegS: 3,
    motionProfileAccSec: 0.05,
    motionProfileDecSec: 0.05,
    leftEnabledAxes: [true, true, true, true, true, true],
    rightEnabledAxes: [true, true, true, true, true, true],
    leftSoftLimitMin: [-200000000, -200000000, -200000000, -200000000, -200000000, -200000000],
    leftSoftLimitMax: [200000000, 200000000, 200000000, 200000000, 200000000, 200000000],
    rightSoftLimitMin: [-200000000, -200000000, -200000000, -200000000, -200000000, -200000000],
    rightSoftLimitMax: [200000000, 200000000, 200000000, 200000000, 200000000, 200000000],
    requireClutch: false,
    stabilityMode: 'free',
    tcpFallbackPort: 12345,
    gripperTeleop: {
      enabled: false,
      loopHz: 100,
      leftGapMinMm: 0.0,
      leftGapMaxMm: 25.0,
      rightGapMinMm: 0.0,
      rightGapMaxMm: 25.0,
      openThreshold: 0.30,
      closeThreshold: 0.70,
      gripSpeed: 128,
      gripTorque: 192,
      releaseSpeed: 255,
      releaseTorque: 64,
      objectDetectMargin: 10,
      buttonFallback: true,
      diagLog: false,
    },
  },
  wsl: {
    distro: 'Ubuntu-22.04',
    condaEnv: 'lerobot',
    pythonPath: '/home/user/miniconda3/envs/lerobot/bin/python',
    pendingWindowsValidation: true,
  },
}
